### ISSUE TITLE
Access to fetch at 'https://endoflife.date/api/springboot.json' from origin 'xx' has been blocked by CORS policy.

### ISSUE THREAD

**Issue by bameur** [dweber019/backstage-plugins#3]
Hello.

I have a blockage because of the cors policy. I had to do some research with no results. Here is the error message :
Access to fetch at 'https://endoflife.date/api/springboot.json' from origin 'https://xxxxxxx.yy' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Do you have any idea to solve it?

Bests regards

**Comment by dweber019** [comment]
Hi

Can you provide the configuration/annotations you used in your example.

**Comment by bameur** [comment]
Hi.

My config : 
```
# Backstage override configuration for your local development environment
backend:
  database:
    client: pg
    connection:
      host: 192.168.x.x
      port: 5432
      user: backstage
      password: xxxxxxxx

integrations:
  gitlab:
    - apiBaseUrl: https://gitlab.domaine.com/api/v4
      host: gitlab.domaine.com
      token: xxxxxxxxxxxxxxxxxxxxxxxxxxx

sonarqube:
  baseUrl: http://sonar.domaine.com
  apiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  endpoints:
    '/gitlab/api/':
      target: 'https://gitlab.domaine.com/api/v4'
      allowedHeaders: ['Authorization', 'Content-Type']
      headers:
        Accept: application/json 
        Content-Type: application/json

#enableExperimentalRedirectFlow: true
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers: 
    gitlab:
      development:
        clientId: ${AUTH_GITLAB_CLIENT_ID}
        clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
        ## uncomment if using self-hosted GitLab
        audience: https://gitlab.domaine.com
        ## uncomment if using a custom redirect URI
        # callbackUrl: https://${BASE_URL}/api/auth/gitlab/handler/frame
  # see https://backstage.io/docs/auth/autologout
  autologout:
    enabled: true
    idleTimeoutMinutes: 30
    useWorkerTimers: false 
    logoutIfDisconnected: false

catalog:
  providers:
    gitlab:
      yourProviderId:
        host: gitlab.domaine.com
        orgEnabled: true
        # group: org/teams # Required for gitlab.com when `orgEnabled: true`. Optional for self managed. Must not end with slash. Accepts only groups under the provided path (which will be stripped)
        groupPattern: '[\s\S]*' # Optional. Filters found groups based on provided pattern. Defaults to `[\s\S]*`, which means to not filter anything
        schedule: # optional; same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 30 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
```

Error:
![image](https://github.com/dweber019/backstage-plugins/assets/10002139/6ea6526d-7320-4dd8-98a9-9702f2fe23d0)

thank you for your help
